version: '3'

services:

  main: #Описание основного контейнера (у нас их может быть несколько)
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports: 
      - 1488:1488 #основной порт приложения
      - 9229:9229 #для дебага порт
    command: node index.js #команда запуска 
    restart: always


